### PR TITLE
Remove .html

### LINKED ISSUE #23: Remove .html
GHPages creates a copy of the page without the .html, which is cleaner. I'll create a pr fixing this.

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
This resolves #23

### CODE REVIEW

**Comment by Explosion-Scratch** [comment]
Hmm, this makes a 404 issue for repl.it, I'll undo this. Thanks for your help though!

**Comment by JeffaloBob** [comment]
are you using repl.it as an ide?

**Comment by YOYITsM3M8** [comment]
Yes he is

**Comment by JeffaloBob** [comment]
@Explosion-Scratch if you're not on a chromebook or something, you should try using something like VSCode

**Pull request merged**
