### PR TITLE
more stuff

### PR DESCRIPTION
**Pull request by YOYITsM3M8**
more website stuff

### CODE REVIEW

**Comment by YOYITsM3M8** [comment]
@Explosion-Scratch

**Comment by YOYITsM3M8** [comment]
@Explosion-Scratch also u using a free kit of font awesome?
inspect element on their website reveals free font awesome 5 pro https://kit-pro.fontawesome.com/releases/v5.14.0/css/pro.min.css

**Comment by Explosion-Scratch** [comment]
Yeah, I'm using a free web font, I think it looks pretty good.

**Comment by YOYITsM3M8** [comment]
use the pro link

**Pull request merged**
