### PR TITLE
Text typing test

### PR DESCRIPTION
**Pull request by Explosion-Scratch**
Go to /typing.html tell me what you think. I'm not going to merge this until I get some more feedback.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
I mean it's cool, but unnecessary :P

**Comment by Explosion-Scratch** [comment]
> I mean it's cool, but unnecessary :P

Yeah, I guess so. I was thinking it might look good on a resedigned front page with a dark theme...

**Comment by GrahamSH-LLK** [comment]
I really like that!

**Comment by Explosion-Scratch** [comment]
Thanks! :) I'm thinkng on trying to put that on my personal website even if
there's not really a place for it on ScratchAddons.

On Sunday, September 6, 2020, GrahamSH <notifications@github.com> wrote:
> I really like that!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/rY7Vz9WuBTxg7EAIETNDThVxkx7XCkZIT_QAwZIOXC5fH4bTs7Le1DphojS4VIvMzKp3qXt6CnRmS3QF4q4pv3LiZpgu3OKhg00hLcQQo4jr_x-93u98aHLhyOJrXT5VjosrDMOKcaUPoomERdIJumpgeJR_mWvqxT01MAB5wN69Wimcw7GIig1qoZTmgopwYgynUKMfgFahYjlDG7EemAm6m3BOo6uqbYSeCcdWRg=s0-d-e1-ft#https://github.com/notifications/beacon/AOT2P3XBZ6TBTOCJPVJ2SB3SEN3SPA5CNFSM4Q3EFKZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFD7JE4Y.gif>

**Comment by Explosion-Scratch** [comment]
Not going to merge this, working on a new design of the website. I might try to incorporate it somehow.

**Pull request closed without merging**
