### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by YOYITsM3M8**
conflicts idk how to fix them plz help

### CODE REVIEW

**Comment by McJoe21** [comment]
Dark mode is good

**Comment by YOYITsM3M8** [comment]
yes it is

**Comment by Explosion-Scratch** [comment]
Hi there! Sorry to say, but I'm not going to merge this or try to fix the conflicts. I'm working on [this](scratchaddonsrestyle.explosionscratc.repl.co) as a restyle of scratchaddons with dark mode.

**Comment by YOYITsM3M8** [comment]
ah oki

**Pull request closed without merging**
